name: Lint, Test, & Format
on:
  pull_request:
    branches:
      - main
jobs:
  lint-test-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node JS
        uses: actions/setup-node@v3 

      - name: Install all dependencies  
        run: npm install

      - name: Run jest
        run: npm run test

      - name: Run lint
        run: npm run lint

      - name: Run prettier
        run: npm run format